name: flake

on:
  pull_request:
  push:
    branches:
      - main

# env:
#   CACHIX_BINARY_CACHE: altf4llc-os

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v25
        with:
          enable_kvm: true
      # - uses: cachix/cachix-action@v14
      #   with:
      #     authToken: ${{ secrets.ALTF4LLC_CACHIX_AUTH_TOKEN }}
      #     name: ${{ env.CACHIX_BINARY_CACHE }}
      - uses: actions/checkout@v4
      - run: nix develop -c just check

  build:
    needs:
      - check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile:
          - gc-fwd
          - ecs-node
    steps:
      - uses: cachix/install-nix-action@v25
        with:
          enable_kvm: true
      # - uses: cachix/cachix-action@v14
      #   with:
      #     authToken: ${{ secrets.ALTF4LLC_CACHIX_AUTH_TOKEN }}
      #     name: ${{ env.CACHIX_BINARY_CACHE }}
      - uses: actions/checkout@v4
      - run: nix develop -c just build "${{ matrix.profile }}"
